### ISSUE TITLE
关于 m10.music.126.net

### ISSUE THREAD

**Issue by xqq** [acgotaku/NetEaseMusicWorld#1]
查了下  ip 是个湖北黄石电信的网宿 cdn ，海外电信回去会比较绕
可以本地 ping 一发 ws.acgvideo.com，然后把拿到的 ip 直接用作 m10.music.126.net，就会是本地的网宿 cdn 了。比如 220.243.249.3

**Comment by acgotaku** [comment]
机智的大佬！

**Comment by acgotaku** [comment]
@xqq 卧槽 效果非常好啊！

**Comment by acgotaku** [comment]
@xqq 话说这CDN是怎么查出来的 0.0

**Comment by xqq** [comment]
ws.acgvideo.com 是 b 站的网宿 cdn，海外都有点，然后网宿的静态加速节点反正又是对所有服务通用的

**Comment by acgotaku** [comment]
@xqq 那 p1,p2,p3的图片服务器也可以？！

**Comment by xqq** [comment]
其实肯定 cache miss 然后回源了，不过它回源也肯定还是比你直连回国要快

**Comment by xqq** [comment]
不清楚图片用的哪家

**Comment by idiotWu** [comment]
p[1-4] 用的是 http://cloudedge.chinanetcenter.com/

**Comment by acgotaku** [comment]
@idiotWu 这是他家子产品？

**Comment by idiotWu** [comment]
@acgotaku 嗯。。随便试了试歪打正着刚好能用 🙃

**Comment by acgotaku** [comment]
@idiotWu 还有这种操作！！！

**Comment by acgotaku** [comment]
@idiotWu 貌似得到的不是境外地址。。。

**Comment by idiotWu** [comment]
@acgotaku 啊忘记看地址了。。话说 p1 和 m10 好像可以直接上 cdnetworks.com

**Comment by acgotaku** [comment]
@idiotWu 都用的啥黑科技找到的啊

**Comment by idiotWu** [comment]
@acgotaku IP地址库里随便一查…
