### ISSUE TITLE
关于寻找最佳m10的CDN地址

### ISSUE THREAD

**Issue by shuspieler** [acgotaku/NetEaseMusicWorld#3]
那个关闭的issuse一位大佬@xqq 提供了查找最近CDN的网址：ws.acgvideo.com
这个是视频缓存的服务器，网易云音乐解析到这里多数是cache miss然后回源，他们的专线比自己的网络肯定快，但是也还不是最佳解决方案。
我找到了网宿专门缓存网易云音乐的地址：netease.ugcvideoss.ourdvs.com
将m10地址设置成ping这个地址得来的ip，由于可以启用缓存不用回源，音乐加载速度会进一步提高。
在我这里，ping这两个域名结果如下，可见在一个网段，猜想很可能就在同一个机房放着，只是不同的CDN服务不同的场景罢了。
![ping](https://user-images.githubusercontent.com/17698039/44297501-dc709e00-a2d2-11e8-8fe7-e779c75ec4d3.PNG)

**Comment by acgotaku** [comment]
这个感觉也没啥大差距吧  实际速度的差距真能感受的出来么？

**Comment by zidongtuili** [comment]
这个地址好像英国用不了。

我是个外行，不过既然有人提到这个了，我fork了一下这个版本，把m10的调整也整合了，用的是另外一个类似host修改的插件的代码。而且我用的直接就是ws.acgvideo.com，不需要用ping之后的ip。虽然不知道原理，但是把ws.acgvideo.com替换成现在这个就用不了了，改动的地方在[这里](https://github.com/zidongtuili/NetEaseMusicWorld/blob/master/chrome/background.js#L14)
其实就是整合了[这个插件](https://chrome.google.com/webstore/detail/virtual-hosts/aiehidpclglccialeifedhajckcpedom?hl=zh-CN)然后我的代码估计哪里抄错了，插件本身是可以写ip或地址的，但是我改的地方写了ping出来的ip反而现在不行了。

说这些其实想说我也不确定是不是彻底用不了

**Comment by Boneflame** [comment]
刚才突然失效了，换了新ping的cdn地址也不行，m7m8前缀的都添加了的
![screenshot from 2018-08-26 01-30-49](https://user-images.githubusercontent.com/5897713/44623478-d3ce2800-a8cf-11e8-8611-2587fd5797a6.png)

**Comment by zidongtuili** [comment]
现在恢复了吗？我在用，目前没发现异常。只改了m10

**Comment by Boneflame** [comment]
ok了，用的ws.acgvideo.com。只是个别曲目放不了，比如这个：
https://music.163.com/#/song?id=26025710

**Comment by zidongtuili** [comment]
哦，我和楼主的头像比较像。我是试了以后用不了的那个人。。。
