### ISSUE TITLE
关于实现原理的请教

### ISSUE THREAD

**Issue by shuspieler** [acgotaku/NetEaseMusicWorld#4]
多数解锁网易云音乐是通过国内的代理，我想请教这个脚本是添加了一个X-Real-IP 的header项而告诉服务器虽然我的请求ip在国外，但是真是ip是国内的（假装用了代理）。这样这个方案并不需要国内服务器中转。
通过host来解决m10 DNS污染问题。
我的理解正确吗？

**Comment by acgotaku** [comment]
是的
