### ISSUE TITLE
有没有可能在 macOS 网易云客户端上设置呢？

### ISSUE THREAD

**Issue by sarkrui** [acgotaku/NetEaseMusicWorld#6]
Chrome 端实现了~ 为了体验更好一点，想要在 macOS 客户端上也实现，各位有没有什么思路呢？

**Comment by ApolloZhu** [comment]
修改 /etc/hosts

**Comment by sarkdavidson** [comment]
> 修改 /etc/hosts
已经修改 /etc/hosts了，Mac客户端显示正在加载；同样，在路由器端把 hosts 修改了也一样不行，除非使用 Proxifier 把 Netease 全部走 socks5 转国内服务器代理

**Comment by acgotaku** [comment]
原理是修改 Http headers Mac上的话 需要网络权限来做修改吧

**Comment by nondanee** [comment]
@zidongtuili 
用 Quantum 的话什么都不要改，直接 load 就行了，我的版本是 62.0.3

![image](https://user-images.githubusercontent.com/26399680/47263273-f461d980-d530-11e8-913a-0d5492f49fb5.png)

Firefox 里是有 `Chrome.webRequest` 的

![image](https://user-images.githubusercontent.com/26399680/47263296-7f42d400-d531-11e8-9ecf-e8988420bd70.png)

**Comment by zidongtuili** [comment]
@nondanee 这两个是桌面浏览器？Quantum有没有手机版？firefox你的意思是理论上可以，但是没有尝试？
我用了一下yandex的，手机端可以加载chrome插件，是没问题的。就差分享朋友圈了，不想装xp插件修改朋友圈内容

**Comment by nondanee** [comment]
@zidongtuili 
我试了桌面版和手机版插件是生效的

但是，网易云的mobile web上歌单不让听，刷新页面以后不让听，(不过WebIDE能看到都已经把歌曲链接取到了)，而且 Firefox mobile 的"要求桌面版网站"有问题。我去试试yandex

你想试试 firefox 的话看下我的[fork](https://github.com/nondanee/NetEaseMusicWorldPlus)

**Comment by zidongtuili** [comment]
@nondanee 我的[fork](https://github.com/zidongtuili/NetEaseMusicWorld) 现在yandex可以用，没有切换成桌面的，不过yandex第一次会直接显示海外不行，第二次登陆就可以了。忘记哪个是主文件了，添加“解压的插件”我选择不了文件夹，所以选择了一个json文件。也不确定是不是最后这么成功装上的。可能歌单比较特别，你说的歌单是那种各人定制的播放列表？
也就说这个火狐的已经可以听了吗？

**Comment by nondanee** [comment]
@zidongtuili 

第二次登录是什么意思啊？网易云 mobile web 没有登录吧。你说切换到桌面版登录账户？
我试了能听的歌一旦刷新网页就会提示”由于版权保护，您所在的地区暂时无法使用“，不知道怎么解决

试了两边的插件从功能上都是生效的，没什么问题
你我fork的区别只是解决cdn命中失败的方法不一样，其它都一样

**Comment by zidongtuili** [comment]
@nondanee 
就是有的时候直接开网页显示gdpr失败什么的，然后刷新一下就好了。我试了推荐歌单里的歌点开来听不了，然后搜索同一首歌却是可以的。

**Comment by nondanee** [comment]
@zidongtuili 切到电脑版登录一下好像就行了
